### ISSUE TITLE
error found

### ISSUE THREAD

**Issue by anshusoni1995** [jiahaoliang/EE652_LOADng#4]
fatal error: net/rime/rimeaddr.h: No such file or directory

**Comment by mhshd** [comment]
you can add both rimeaddr.h and rimeaddr.c to core/net/rime folder from link below :
[https://github.com/hikob/contiki/tree/master/core/net/rime](url)

**Comment by mhshd** [comment]
you can use rimeaddr.h and rimeaddr.c files, from link below :
[https://github.com/hikob/contiki/tree/master/core/net/rime](https://github.com/hikob/contiki/tree/master/core/net/rime)
